# This example demonstrates the how to refer to input and output artifact paths.
# Referring to the path instead of copy/pasting it prevents errors when paths change.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-path-placeholders-
spec:
  entrypoint: head-lines
  arguments:
    parameters:
    - name: lines-count
      value: '3'
    artifacts:
    - name: text
      raw:
        data: |
          1
          2
          3
          4
          5
  templates:
  - name: head-lines
    inputs:
      parameters:
      - name: lines-count
      artifacts:
      - name: text
        path: /inputs/text/data
    outputs:
      parameters:
      - name: actual-lines-count
        valueFrom:
          path: /outputs/actual-lines-count/data
      artifacts:
      - name: text
        path: /outputs/text/data
    script:
      image: busybox
      command: [sh, -c]
      source: |
        mkdir -p "$(dirname $OUTPUT_TEXT_PATH)" "$(dirname $OUTPUT_ACTUAL_LINES_COUNT_PATH)"
        head -n "$INPUT_LINES_COUNT" < "$INPUT_TEXT_PATH" | tee "$OUTPUT_TEXT_PATH" | wc -l > "$OUTPUT_ACTUAL_LINES_COUNT_PATH"
      env:
        - name: OUTPUT_TEXT_PATH
          value: "{{outputs.artifacts.text.path}}"
        - name: OUTPUT_ACTUAL_LINES_COUNT_PATH 
          value: "{{outputs.parameters.actual-lines-count.path}}"
        - name: INPUT_TEXT_PATH
          value: "{{inputs.artifacts.text.path}}"
        - name: INPUT_LINES_COUNT
          value: "{{inputs.parameters.lines-count}}"
