apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-
spec:
  entrypoint: loop-example
  templates:
  - name: loop-example
    steps:
    - - name: print-message-loop
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withItems:
        - hello world
        - goodbye world

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: busybox
      command: [printenv]
      args: ["MESSAGE"]
      env:
      - name: MESSAGE
        value: "{{inputs.parameters.message}}"
