# This example illustrates how to iterate serially over a sequence using a counter.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: recursive-loop-
spec:
  entrypoint: plan
  templates:
    - name: plan
      steps:
        - - name: recurse
            template: loop
            arguments:
              parameters:
                - name: counter
                  value: '0'
                - name: limit
                  value: '10'
    - name: loop
      inputs:
        parameters:
          - name: counter
          - name: limit
      steps:
        - - name: iterate-counter
            template: counter-iteration
            arguments:
              parameters:
                - name: counter
                  value: "{{inputs.parameters.counter}}"
        - - name: continue
            template: loop
            when: "{{steps.iterate-counter.outputs.result}} < {{inputs.parameters.limit}}"
            arguments:
              parameters:
                - name: counter
                  value: "{{steps.iterate-counter.outputs.result}}"
                - name: limit
                  value: "{{inputs.parameters.limit}}"

    - name: counter-iteration
      inputs:
        parameters:
          - name: counter
      container:
        image: busybox
        command: [sh, -c, 'expr "$COUNTER" + 1']
        env:
        - name: COUNTER
          value: "{{inputs.parameters.counter}}"
