name: Pre-build dev container Image

on:
  push:
    branches:
      - main
      - prebuild-devcontainer-image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build_devcontainer:
    #if: github.repository == 'argoproj/argo-workflows'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
        with:
          version: v0.22.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dev container cache image
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3
        env:
          CACHE_IMAGE: ghcr.io/${{ github.repository_owner }}/argo-workflows-devcontainer:latest
        with:
          push: never
          cacheFrom: type=registry,ref=${{ env.CACHE_IMAGE }}
          cacheTo: type=registry,ref=${{ env.CACHE_IMAGE }},compression=zstd,mode=max